CREATE TABLE IF NOT EXISTS Session (
    Id VARCHAR(36) PRIMARY KEY,
    UserId INT NOT NULL,
    VerificationId VARCHAR(36) NOT NULL,
    ExpiryDate DATETIME NOT NULL,
    Complete BOOLEAN DEFAULT FALSE,
    Revoked BOOLEAN DEFAULT FALSE,
    CreatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    UpdatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (UserID) REFERENCES Users(Id),
    FOREIGN KEY (VerificationId) REFERENCES Verification(Id)
);

